apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-frontend.fullname" . }}
  labels:
    {{- include "todo-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "todo-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todo-frontend.fullname" . }}-config
                  key: NEXT_PUBLIC_API_URL
            - name: BETTER_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todo-frontend.fullname" . }}-config
                  key: BETTER_AUTH_URL
            - name: BETTER_AUTH_TRUSTED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todo-frontend.fullname" . }}-config
                  key: BETTER_AUTH_TRUSTED_ORIGINS
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "todo-frontend.fullname" . }}-secrets
                  key: DATABASE_URL
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "todo-frontend.fullname" . }}-secrets
                  key: BETTER_AUTH_SECRET
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 1 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 1 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
